### ISSUE TITLE
Deep Diffing?

### ISSUE THREAD

**Issue by FlorianWendelborn** [srcagency/object-diff#7]
Can this package be used to calculate a recursive diff?

E.g.

```javascript
const a = {
	data: {
		a: 'A',
		changes: false
	}
}
const b = {
	data: {
		a: 'B',
		changes: false
	}
}
console.log(diff(a, b))
// {data:{a:'B'}}
```

**Comment by tjconcept** [comment]
I'm afraid not.

**Comment by scriby** [comment]
Not only can it not be used to calculate recursive diffs, it doesn't perform deep equality checks either, so any deep structures you have will always be included in the diff.

**Comment by tjconcept** [comment]
My intuition is that you should not have "generically" nesting. Instead, I would do something like:

```js
{
  data: diff(a.data, b.data);
}
```

So it's actually a design choice. I might change my opinion of course, but even then I think it should be another project.
For the level of flexibility described by @scriby, I think you're better of with a "object walking"-library, so that you can control the equality check and output completely.
